// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package chat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReceiveRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Amount               int32    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Skip                 int32    `protobuf:"varint,3,opt,name=skip,proto3" json:"skip,omitempty"`
	From                 int64    `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveRequest) Reset()         { *m = ReceiveRequest{} }
func (m *ReceiveRequest) String() string { return proto.CompactTextString(m) }
func (*ReceiveRequest) ProtoMessage()    {}
func (*ReceiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *ReceiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveRequest.Unmarshal(m, b)
}
func (m *ReceiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveRequest.Marshal(b, m, deterministic)
}
func (m *ReceiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveRequest.Merge(m, src)
}
func (m *ReceiveRequest) XXX_Size() int {
	return xxx_messageInfo_ReceiveRequest.Size(m)
}
func (m *ReceiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveRequest proto.InternalMessageInfo

func (m *ReceiveRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ReceiveRequest) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ReceiveRequest) GetSkip() int32 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *ReceiveRequest) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

type ReceiveNewRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveNewRequest) Reset()         { *m = ReceiveNewRequest{} }
func (m *ReceiveNewRequest) String() string { return proto.CompactTextString(m) }
func (*ReceiveNewRequest) ProtoMessage()    {}
func (*ReceiveNewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *ReceiveNewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveNewRequest.Unmarshal(m, b)
}
func (m *ReceiveNewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveNewRequest.Marshal(b, m, deterministic)
}
func (m *ReceiveNewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveNewRequest.Merge(m, src)
}
func (m *ReceiveNewRequest) XXX_Size() int {
	return xxx_messageInfo_ReceiveNewRequest.Size(m)
}
func (m *ReceiveNewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveNewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveNewRequest proto.InternalMessageInfo

func (m *ReceiveNewRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type ReceiveResponse struct {
	Chats                []*UserChat `protobuf:"bytes,1,rep,name=Chats,proto3" json:"Chats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReceiveResponse) Reset()         { *m = ReceiveResponse{} }
func (m *ReceiveResponse) String() string { return proto.CompactTextString(m) }
func (*ReceiveResponse) ProtoMessage()    {}
func (*ReceiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *ReceiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveResponse.Unmarshal(m, b)
}
func (m *ReceiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveResponse.Marshal(b, m, deterministic)
}
func (m *ReceiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveResponse.Merge(m, src)
}
func (m *ReceiveResponse) XXX_Size() int {
	return xxx_messageInfo_ReceiveResponse.Size(m)
}
func (m *ReceiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveResponse proto.InternalMessageInfo

func (m *ReceiveResponse) GetChats() []*UserChat {
	if m != nil {
		return m.Chats
	}
	return nil
}

type UserChat struct {
	Id                   string   `protobuf:"bytes,8,opt,name=Id,proto3" json:"Id,omitempty"`
	FromID               string   `protobuf:"bytes,1,opt,name=FromID,proto3" json:"FromID,omitempty"`
	ToID                 string   `protobuf:"bytes,2,opt,name=ToID,proto3" json:"ToID,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	ReceivedAt           int64    `protobuf:"varint,4,opt,name=ReceivedAt,proto3" json:"ReceivedAt,omitempty"`
	ReadAt               int64    `protobuf:"varint,5,opt,name=ReadAt,proto3" json:"ReadAt,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Deleted              bool     `protobuf:"varint,7,opt,name=Deleted,proto3" json:"Deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserChat) Reset()         { *m = UserChat{} }
func (m *UserChat) String() string { return proto.CompactTextString(m) }
func (*UserChat) ProtoMessage()    {}
func (*UserChat) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *UserChat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserChat.Unmarshal(m, b)
}
func (m *UserChat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserChat.Marshal(b, m, deterministic)
}
func (m *UserChat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserChat.Merge(m, src)
}
func (m *UserChat) XXX_Size() int {
	return xxx_messageInfo_UserChat.Size(m)
}
func (m *UserChat) XXX_DiscardUnknown() {
	xxx_messageInfo_UserChat.DiscardUnknown(m)
}

var xxx_messageInfo_UserChat proto.InternalMessageInfo

func (m *UserChat) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserChat) GetFromID() string {
	if m != nil {
		return m.FromID
	}
	return ""
}

func (m *UserChat) GetToID() string {
	if m != nil {
		return m.ToID
	}
	return ""
}

func (m *UserChat) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserChat) GetReceivedAt() int64 {
	if m != nil {
		return m.ReceivedAt
	}
	return 0
}

func (m *UserChat) GetReadAt() int64 {
	if m != nil {
		return m.ReadAt
	}
	return 0
}

func (m *UserChat) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *UserChat) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type SendRequest struct {
	FromUserID           string   `protobuf:"bytes,1,opt,name=fromUserID,proto3" json:"fromUserID,omitempty"`
	ToUserID             string   `protobuf:"bytes,2,opt,name=toUserID,proto3" json:"toUserID,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{4}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetFromUserID() string {
	if m != nil {
		return m.FromUserID
	}
	return ""
}

func (m *SendRequest) GetToUserID() string {
	if m != nil {
		return m.ToUserID
	}
	return ""
}

func (m *SendRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ReceiveRequest)(nil), "ReceiveRequest")
	proto.RegisterType((*ReceiveNewRequest)(nil), "ReceiveNewRequest")
	proto.RegisterType((*ReceiveResponse)(nil), "ReceiveResponse")
	proto.RegisterType((*UserChat)(nil), "UserChat")
	proto.RegisterType((*SendRequest)(nil), "SendRequest")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x41, 0x6e, 0xea, 0x30,
	0x10, 0x95, 0x21, 0x40, 0x32, 0x7c, 0xc1, 0xaf, 0x17, 0x95, 0x85, 0x2a, 0x88, 0xb2, 0x8a, 0xd4,
	0xca, 0x8b, 0xf4, 0x04, 0x15, 0xa8, 0x52, 0x16, 0x65, 0xe1, 0x96, 0x03, 0xa4, 0x64, 0x5a, 0x50,
	0x1b, 0x4c, 0x63, 0x53, 0xce, 0xd0, 0xdb, 0xf5, 0x48, 0x95, 0x8d, 0x13, 0x42, 0x59, 0x74, 0x37,
	0xef, 0x8d, 0xec, 0x37, 0xef, 0xcd, 0x00, 0x2c, 0x57, 0x99, 0xe6, 0xdb, 0x52, 0x6a, 0x19, 0xad,
	0x60, 0x20, 0x70, 0x89, 0xeb, 0x4f, 0x14, 0xf8, 0xb1, 0x43, 0xa5, 0xe9, 0x25, 0x74, 0x77, 0x0a,
	0xcb, 0x74, 0xc6, 0x48, 0x48, 0xe2, 0x40, 0x38, 0x64, 0xf8, 0xac, 0x90, 0xbb, 0x8d, 0x66, 0xad,
	0x90, 0xc4, 0x1d, 0xe1, 0x10, 0xa5, 0xe0, 0xa9, 0xb7, 0xf5, 0x96, 0xb5, 0x2d, 0x6b, 0x6b, 0xc3,
	0xbd, 0x94, 0xb2, 0x60, 0x5e, 0x48, 0xe2, 0xb6, 0xb0, 0x75, 0x74, 0x0d, 0x17, 0x4e, 0x69, 0x8e,
	0xfb, 0x3f, 0xc4, 0xa2, 0x04, 0x86, 0xf5, 0x58, 0x6a, 0x2b, 0x37, 0x0a, 0xe9, 0x04, 0x3a, 0xd3,
	0x55, 0xa6, 0x15, 0x23, 0x61, 0x3b, 0xee, 0x27, 0x01, 0x5f, 0x28, 0x2c, 0x0d, 0x23, 0x0e, 0x7c,
	0xf4, 0x4d, 0xc0, 0xaf, 0x38, 0x3a, 0x80, 0x56, 0x9a, 0x33, 0xdf, 0x7e, 0xda, 0x4a, 0x73, 0x23,
	0x74, 0x5f, 0xca, 0xe2, 0x28, 0x74, 0x40, 0x66, 0xd2, 0x27, 0x99, 0xce, 0xac, 0xa7, 0x40, 0xd8,
	0x9a, 0x32, 0xe8, 0x3d, 0xa0, 0x52, 0xd9, 0x2b, 0x5a, 0x53, 0x81, 0xa8, 0x20, 0x1d, 0x03, 0xb8,
	0xb1, 0xf2, 0x3b, 0xed, 0xdc, 0x35, 0x18, 0xa3, 0x22, 0x30, 0x33, 0xbd, 0x8e, 0xed, 0x39, 0x44,
	0xaf, 0x20, 0x98, 0x96, 0x98, 0x69, 0xfb, 0xac, 0x6b, 0x5b, 0x47, 0xc2, 0xe8, 0xcd, 0xf0, 0x1d,
	0x35, 0xe6, 0xac, 0x17, 0x92, 0xd8, 0x17, 0x15, 0x8c, 0x96, 0xd0, 0x7f, 0xc4, 0x4d, 0x5e, 0xa5,
	0x35, 0x06, 0x30, 0x51, 0x2e, 0x9a, 0x89, 0x35, 0x18, 0x3a, 0x02, 0x5f, 0x4b, 0xd7, 0x3d, 0x18,
	0xaa, 0xb1, 0x11, 0x29, 0x4e, 0x4d, 0x39, 0x18, 0x01, 0xf8, 0x55, 0xc8, 0xc9, 0x17, 0x01, 0xcf,
	0x5c, 0x07, 0x9d, 0x80, 0x67, 0x94, 0xe9, 0x3f, 0xde, 0x18, 0x60, 0x14, 0xf0, 0x7a, 0x1d, 0x37,
	0xd0, 0x73, 0xc6, 0xe9, 0x90, 0x9f, 0x9e, 0xd0, 0xe8, 0x3f, 0xff, 0xbd, 0xbc, 0xa4, 0x0e, 0x6e,
	0x8e, 0x7b, 0x4a, 0xf9, 0xd9, 0x25, 0x9c, 0xbf, 0x79, 0xee, 0xda, 0x0b, 0xbd, 0xfd, 0x09, 0x00,
	0x00, 0xff, 0xff, 0xc8, 0xba, 0xd2, 0x09, 0xaf, 0x02, 0x00, 0x00,
}
