// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package event

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewUserEvent struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewUserEvent) Reset()         { *m = NewUserEvent{} }
func (m *NewUserEvent) String() string { return proto.CompactTextString(m) }
func (*NewUserEvent) ProtoMessage()    {}
func (*NewUserEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *NewUserEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewUserEvent.Unmarshal(m, b)
}
func (m *NewUserEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewUserEvent.Marshal(b, m, deterministic)
}
func (m *NewUserEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewUserEvent.Merge(m, src)
}
func (m *NewUserEvent) XXX_Size() int {
	return xxx_messageInfo_NewUserEvent.Size(m)
}
func (m *NewUserEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_NewUserEvent.DiscardUnknown(m)
}

var xxx_messageInfo_NewUserEvent proto.InternalMessageInfo

func (m *NewUserEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewUserEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *NewUserEvent) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*NewUserEvent)(nil), "NewUserEvent")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 110 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2d, 0x4b, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x0a, 0xe1, 0xe2, 0xf1, 0x4b, 0x2d, 0x0f, 0x2d,
	0x4e, 0x2d, 0x72, 0x05, 0x89, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x31, 0x65, 0xa6, 0x08, 0xc9, 0x70, 0x71, 0x96, 0x64, 0xe6, 0xa6, 0x16, 0x97, 0x24,
	0xe6, 0x16, 0x48, 0x30, 0x29, 0x30, 0x6a, 0x30, 0x07, 0x21, 0x04, 0x84, 0xc4, 0xb8, 0xd8, 0x4a,
	0x8b, 0x53, 0x8b, 0x3c, 0x5d, 0x24, 0x98, 0xc1, 0x3a, 0xa0, 0xbc, 0x24, 0x36, 0xb0, 0xe1, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08, 0x18, 0x0c, 0x71, 0x6b, 0x00, 0x00, 0x00,
}
