// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package profile

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchResponse struct {
	Users                []*SearchUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{1}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetUsers() []*SearchUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type SearchUser struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchUser) Reset()         { *m = SearchUser{} }
func (m *SearchUser) String() string { return proto.CompactTextString(m) }
func (*SearchUser) ProtoMessage()    {}
func (*SearchUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{2}
}

func (m *SearchUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchUser.Unmarshal(m, b)
}
func (m *SearchUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchUser.Marshal(b, m, deterministic)
}
func (m *SearchUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchUser.Merge(m, src)
}
func (m *SearchUser) XXX_Size() int {
	return xxx_messageInfo_SearchUser.Size(m)
}
func (m *SearchUser) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchUser.DiscardUnknown(m)
}

var xxx_messageInfo_SearchUser proto.InternalMessageInfo

func (m *SearchUser) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SearchUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetInfoRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRequest) Reset()         { *m = GetInfoRequest{} }
func (m *GetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetInfoRequest) ProtoMessage()    {}
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{3}
}

func (m *GetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRequest.Unmarshal(m, b)
}
func (m *GetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRequest.Merge(m, src)
}
func (m *GetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetInfoRequest.Size(m)
}
func (m *GetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRequest proto.InternalMessageInfo

func (m *GetInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetInfoResponse struct {
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Birth                int64    `protobuf:"varint,4,opt,name=Birth,proto3" json:"Birth,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=Status,proto3" json:"Status,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=Email,proto3" json:"Email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoResponse) Reset()         { *m = GetInfoResponse{} }
func (m *GetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetInfoResponse) ProtoMessage()    {}
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{4}
}

func (m *GetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoResponse.Unmarshal(m, b)
}
func (m *GetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoResponse.Merge(m, src)
}
func (m *GetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetInfoResponse.Size(m)
}
func (m *GetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoResponse proto.InternalMessageInfo

func (m *GetInfoResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetInfoResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *GetInfoResponse) GetBirth() int64 {
	if m != nil {
		return m.Birth
	}
	return 0
}

func (m *GetInfoResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetInfoResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UpdateStatusRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	NewStatus            string   `protobuf:"bytes,2,opt,name=newStatus,proto3" json:"newStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateStatusRequest) Reset()         { *m = UpdateStatusRequest{} }
func (m *UpdateStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStatusRequest) ProtoMessage()    {}
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{5}
}

func (m *UpdateStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStatusRequest.Unmarshal(m, b)
}
func (m *UpdateStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStatusRequest.Marshal(b, m, deterministic)
}
func (m *UpdateStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStatusRequest.Merge(m, src)
}
func (m *UpdateStatusRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStatusRequest.Size(m)
}
func (m *UpdateStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStatusRequest proto.InternalMessageInfo

func (m *UpdateStatusRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateStatusRequest) GetNewStatus() string {
	if m != nil {
		return m.NewStatus
	}
	return ""
}

type UpdateEmailRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	NewEmail             string   `protobuf:"bytes,2,opt,name=newEmail,proto3" json:"newEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmailRequest) Reset()         { *m = UpdateEmailRequest{} }
func (m *UpdateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEmailRequest) ProtoMessage()    {}
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{6}
}

func (m *UpdateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmailRequest.Unmarshal(m, b)
}
func (m *UpdateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmailRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmailRequest.Merge(m, src)
}
func (m *UpdateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEmailRequest.Size(m)
}
func (m *UpdateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmailRequest proto.InternalMessageInfo

func (m *UpdateEmailRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateEmailRequest) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

type ConfirmEmailRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	EmailToken           string   `protobuf:"bytes,2,opt,name=emailToken,proto3" json:"emailToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmEmailRequest) Reset()         { *m = ConfirmEmailRequest{} }
func (m *ConfirmEmailRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmEmailRequest) ProtoMessage()    {}
func (*ConfirmEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{7}
}

func (m *ConfirmEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmEmailRequest.Unmarshal(m, b)
}
func (m *ConfirmEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmEmailRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmEmailRequest.Merge(m, src)
}
func (m *ConfirmEmailRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmEmailRequest.Size(m)
}
func (m *ConfirmEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmEmailRequest proto.InternalMessageInfo

func (m *ConfirmEmailRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ConfirmEmailRequest) GetEmailToken() string {
	if m != nil {
		return m.EmailToken
	}
	return ""
}

type UpdateInfoRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Birth                int64    `protobuf:"varint,4,opt,name=Birth,proto3" json:"Birth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInfoRequest) Reset()         { *m = UpdateInfoRequest{} }
func (m *UpdateInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateInfoRequest) ProtoMessage()    {}
func (*UpdateInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{8}
}

func (m *UpdateInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfoRequest.Unmarshal(m, b)
}
func (m *UpdateInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfoRequest.Merge(m, src)
}
func (m *UpdateInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateInfoRequest.Size(m)
}
func (m *UpdateInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfoRequest proto.InternalMessageInfo

func (m *UpdateInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateInfoRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateInfoRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdateInfoRequest) GetBirth() int64 {
	if m != nil {
		return m.Birth
	}
	return 0
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{9}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto.RegisterType((*SearchUser)(nil), "SearchUser")
	proto.RegisterType((*GetInfoRequest)(nil), "GetInfoRequest")
	proto.RegisterType((*GetInfoResponse)(nil), "GetInfoResponse")
	proto.RegisterType((*UpdateStatusRequest)(nil), "UpdateStatusRequest")
	proto.RegisterType((*UpdateEmailRequest)(nil), "UpdateEmailRequest")
	proto.RegisterType((*ConfirmEmailRequest)(nil), "ConfirmEmailRequest")
	proto.RegisterType((*UpdateInfoRequest)(nil), "UpdateInfoRequest")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504) }

var fileDescriptor_744bf7a47b381504 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xdb, 0x4e, 0xea, 0x40,
	0x14, 0x4d, 0xb9, 0x14, 0xd8, 0x1c, 0xe0, 0x38, 0x10, 0xd3, 0x34, 0xc6, 0xe0, 0x24, 0x26, 0x35,
	0xea, 0x98, 0xc0, 0x8b, 0xcf, 0xde, 0x89, 0x97, 0x87, 0x22, 0x1f, 0x50, 0x75, 0x08, 0x8d, 0xd0,
	0x96, 0x99, 0x69, 0x88, 0xf1, 0x23, 0xfc, 0x05, 0x3f, 0xd5, 0xb4, 0x33, 0xb4, 0xe5, 0x62, 0xe0,
	0xc1, 0xb7, 0xae, 0xb5, 0xf7, 0xac, 0xae, 0x99, 0xb5, 0x37, 0xd4, 0x02, 0xe6, 0x0f, 0xdd, 0x31,
	0x25, 0x01, 0xf3, 0x85, 0x8f, 0x0f, 0xa1, 0xd6, 0xa7, 0x0e, 0x7b, 0x1d, 0xd9, 0x74, 0x1a, 0x52,
	0x2e, 0x50, 0x0b, 0x8a, 0xd3, 0x90, 0xb2, 0x0f, 0x43, 0x6b, 0x6b, 0x56, 0xc5, 0x96, 0x00, 0x77,
	0xa1, 0x3e, 0x6f, 0xe3, 0x81, 0xef, 0x71, 0x8a, 0x0e, 0xa0, 0x18, 0x72, 0xca, 0xb8, 0xa1, 0xb5,
	0xf3, 0x56, 0xb5, 0x53, 0x25, 0xb2, 0x3e, 0xe0, 0x94, 0xd9, 0xb2, 0x82, 0xcf, 0x01, 0x52, 0x12,
	0xed, 0x82, 0x1e, 0xd1, 0xbd, 0x2b, 0xa5, 0xac, 0x10, 0x42, 0x50, 0xf0, 0x9c, 0x09, 0x35, 0x72,
	0x31, 0x1b, 0x7f, 0x63, 0x0b, 0xea, 0xb7, 0x54, 0xf4, 0xbc, 0xa1, 0x3f, 0xb7, 0xf5, 0xcb, 0x69,
	0xfc, 0xa5, 0x41, 0x23, 0x69, 0x55, 0xd6, 0xf6, 0xa0, 0x72, 0xe3, 0x32, 0x2e, 0x9e, 0x52, 0xd9,
	0x94, 0x40, 0x26, 0x94, 0x1f, 0x1c, 0x55, 0xcc, 0xc7, 0xc5, 0x04, 0x47, 0x97, 0xbf, 0x70, 0x99,
	0x18, 0x19, 0x85, 0xb6, 0x66, 0xe5, 0x6d, 0x09, 0xa2, 0x7f, 0xf7, 0x85, 0x23, 0x42, 0x6e, 0x14,
	0xe5, 0xbf, 0x25, 0x8a, 0xba, 0xaf, 0x27, 0x8e, 0x3b, 0x36, 0x74, 0xf9, 0x54, 0x31, 0xc0, 0xf7,
	0xd0, 0x1c, 0x04, 0x6f, 0x8e, 0xa0, 0xb2, 0x6b, 0xc3, 0x05, 0x22, 0xb3, 0x1e, 0x9d, 0x29, 0x7d,
	0x65, 0x36, 0x21, 0xf0, 0x1d, 0x20, 0x29, 0x16, 0x6b, 0x6f, 0xd2, 0x32, 0xa1, 0xec, 0xd1, 0x99,
	0xf4, 0x24, 0xa5, 0x12, 0x8c, 0x1f, 0xa1, 0x79, 0xe9, 0x7b, 0x43, 0x97, 0x4d, 0xb6, 0x92, 0xda,
	0x07, 0xa0, 0x51, 0xdf, 0xb3, 0xff, 0x4e, 0x3d, 0x25, 0x96, 0x61, 0xf0, 0x27, 0xec, 0x48, 0x63,
	0x5b, 0x84, 0xf4, 0xd7, 0x81, 0x60, 0x80, 0xf2, 0x3c, 0xec, 0xce, 0x77, 0x0e, 0x4a, 0x6a, 0xa4,
	0xd1, 0x31, 0x40, 0x6a, 0x0a, 0x21, 0xb2, 0xe2, 0xd0, 0xac, 0x90, 0x64, 0x4a, 0xce, 0xe0, 0x5f,
	0x36, 0x27, 0xd4, 0x22, 0x6b, 0x62, 0xcb, 0x1e, 0x38, 0x85, 0x6a, 0x26, 0x0b, 0xd4, 0x24, 0xab,
	0xc9, 0x2c, 0xe9, 0x67, 0x1f, 0x1c, 0xb5, 0xc8, 0x9a, 0xf7, 0xcf, 0x1e, 0x38, 0x81, 0x92, 0x9a,
	0x64, 0xd4, 0x20, 0x8b, 0xe3, 0x6f, 0xfe, 0x27, 0xcb, 0x43, 0x7e, 0x04, 0xba, 0x5c, 0x2e, 0x54,
	0x27, 0x0b, 0x1b, 0x6c, 0x36, 0xc8, 0xe2, 0xaa, 0xbe, 0xe8, 0xf1, 0xaa, 0x77, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xd8, 0x01, 0xc2, 0xb6, 0xfb, 0x03, 0x00, 0x00,
}
