// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package profile

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateStatusRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	NewStatus            string   `protobuf:"bytes,2,opt,name=newStatus,proto3" json:"newStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateStatusRequest) Reset()         { *m = UpdateStatusRequest{} }
func (m *UpdateStatusRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStatusRequest) ProtoMessage()    {}
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *UpdateStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStatusRequest.Unmarshal(m, b)
}
func (m *UpdateStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStatusRequest.Marshal(b, m, deterministic)
}
func (m *UpdateStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStatusRequest.Merge(m, src)
}
func (m *UpdateStatusRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStatusRequest.Size(m)
}
func (m *UpdateStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStatusRequest proto.InternalMessageInfo

func (m *UpdateStatusRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateStatusRequest) GetNewStatus() string {
	if m != nil {
		return m.NewStatus
	}
	return ""
}

type UpdateEmailRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	NewEmail             string   `protobuf:"bytes,2,opt,name=newEmail,proto3" json:"newEmail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateEmailRequest) Reset()         { *m = UpdateEmailRequest{} }
func (m *UpdateEmailRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateEmailRequest) ProtoMessage()    {}
func (*UpdateEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{1}
}

func (m *UpdateEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateEmailRequest.Unmarshal(m, b)
}
func (m *UpdateEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateEmailRequest.Marshal(b, m, deterministic)
}
func (m *UpdateEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateEmailRequest.Merge(m, src)
}
func (m *UpdateEmailRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateEmailRequest.Size(m)
}
func (m *UpdateEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateEmailRequest proto.InternalMessageInfo

func (m *UpdateEmailRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateEmailRequest) GetNewEmail() string {
	if m != nil {
		return m.NewEmail
	}
	return ""
}

type ConfirmEmailRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	EmailToken           string   `protobuf:"bytes,2,opt,name=emailToken,proto3" json:"emailToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmEmailRequest) Reset()         { *m = ConfirmEmailRequest{} }
func (m *ConfirmEmailRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmEmailRequest) ProtoMessage()    {}
func (*ConfirmEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{2}
}

func (m *ConfirmEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmEmailRequest.Unmarshal(m, b)
}
func (m *ConfirmEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmEmailRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmEmailRequest.Merge(m, src)
}
func (m *ConfirmEmailRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmEmailRequest.Size(m)
}
func (m *ConfirmEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmEmailRequest proto.InternalMessageInfo

func (m *ConfirmEmailRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ConfirmEmailRequest) GetEmailToken() string {
	if m != nil {
		return m.EmailToken
	}
	return ""
}

type UpdateInfoRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Birth                int64    `protobuf:"varint,4,opt,name=Birth,proto3" json:"Birth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateInfoRequest) Reset()         { *m = UpdateInfoRequest{} }
func (m *UpdateInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateInfoRequest) ProtoMessage()    {}
func (*UpdateInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{3}
}

func (m *UpdateInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateInfoRequest.Unmarshal(m, b)
}
func (m *UpdateInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateInfoRequest.Marshal(b, m, deterministic)
}
func (m *UpdateInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateInfoRequest.Merge(m, src)
}
func (m *UpdateInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateInfoRequest.Size(m)
}
func (m *UpdateInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateInfoRequest proto.InternalMessageInfo

func (m *UpdateInfoRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *UpdateInfoRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UpdateInfoRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UpdateInfoRequest) GetBirth() int64 {
	if m != nil {
		return m.Birth
	}
	return 0
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UpdateStatusRequest)(nil), "UpdateStatusRequest")
	proto.RegisterType((*UpdateEmailRequest)(nil), "UpdateEmailRequest")
	proto.RegisterType((*ConfirmEmailRequest)(nil), "ConfirmEmailRequest")
	proto.RegisterType((*UpdateInfoRequest)(nil), "UpdateInfoRequest")
	proto.RegisterType((*Response)(nil), "Response")
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504) }

var fileDescriptor_744bf7a47b381504 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xdd, 0x4a, 0xfb, 0x40,
	0x10, 0xc5, 0xc9, 0xbf, 0x7f, 0x6b, 0x33, 0xea, 0x85, 0x93, 0x20, 0xa1, 0x88, 0x94, 0x5c, 0x15,
	0xc4, 0x15, 0xf4, 0x0d, 0xfc, 0xc2, 0xe2, 0xc7, 0x45, 0xd4, 0x07, 0x58, 0x71, 0x82, 0x8b, 0xcd,
	0x6e, 0xdc, 0xdd, 0xd0, 0x0b, 0x1f, 0xd0, 0xd7, 0x92, 0x66, 0x37, 0xed, 0x62, 0x0b, 0xf6, 0xf2,
	0xcc, 0xce, 0xfc, 0x38, 0x33, 0x67, 0x61, 0xaf, 0xd6, 0xaa, 0x14, 0x53, 0x62, 0xb5, 0x56, 0x56,
	0xe5, 0x77, 0x90, 0xbc, 0xd4, 0x6f, 0xdc, 0xd2, 0x93, 0xe5, 0xb6, 0x31, 0x05, 0x7d, 0x36, 0x64,
	0x2c, 0x1e, 0x40, 0xbf, 0x31, 0xa4, 0x27, 0x57, 0x59, 0x34, 0x8a, 0xc6, 0x71, 0xe1, 0x15, 0x1e,
	0x42, 0x2c, 0x69, 0xe6, 0x7a, 0xb3, 0x7f, 0xed, 0xd3, 0xb2, 0x90, 0xdf, 0x02, 0x3a, 0xd8, 0x75,
	0xc5, 0xc5, 0xf4, 0x2f, 0xd6, 0x10, 0x06, 0x92, 0x66, 0x6d, 0xab, 0x47, 0x2d, 0x74, 0xfe, 0x00,
	0xc9, 0xa5, 0x92, 0xa5, 0xd0, 0xd5, 0x46, 0xa8, 0x23, 0x00, 0x9a, 0xf7, 0x3d, 0xab, 0x0f, 0x92,
	0x1e, 0x16, 0x54, 0xf2, 0x2f, 0xd8, 0x77, 0xc6, 0x26, 0xb2, 0x54, 0x1b, 0xec, 0x78, 0x23, 0xb4,
	0xb1, 0x8f, 0xbc, 0xa2, 0x6e, 0xc7, 0x45, 0x61, 0xee, 0xfa, 0x9e, 0xfb, 0xc7, 0x9e, 0x73, 0xdd,
	0x69, 0x4c, 0x61, 0xeb, 0x42, 0x68, 0xfb, 0x9e, 0xfd, 0x1f, 0x45, 0xe3, 0x5e, 0xe1, 0x44, 0x0e,
	0x30, 0x28, 0xc8, 0xd4, 0x4a, 0x1a, 0x3a, 0xfb, 0x8e, 0x60, 0xdb, 0x07, 0x80, 0xc7, 0x00, 0x4b,
	0x53, 0x88, 0x6c, 0xc5, 0xe1, 0x30, 0x66, 0xdd, 0x20, 0x9e, 0xc2, 0x6e, 0x98, 0x13, 0xa6, 0x6c,
	0x4d, 0x6c, 0xe1, 0xc0, 0x09, 0xec, 0x04, 0x59, 0x60, 0xc2, 0x56, 0x93, 0xf9, 0xc5, 0x0f, 0x0f,
	0x8e, 0x29, 0x5b, 0x73, 0xff, 0x60, 0xe0, 0xb5, 0xdf, 0xfe, 0x9f, 0xf3, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x84, 0x87, 0x60, 0x8b, 0x50, 0x02, 0x00, 0x00,
}
