// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckPasswordRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPasswordRequest) Reset()         { *m = CheckPasswordRequest{} }
func (m *CheckPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*CheckPasswordRequest) ProtoMessage()    {}
func (*CheckPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *CheckPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPasswordRequest.Unmarshal(m, b)
}
func (m *CheckPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPasswordRequest.Marshal(b, m, deterministic)
}
func (m *CheckPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPasswordRequest.Merge(m, src)
}
func (m *CheckPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_CheckPasswordRequest.Size(m)
}
func (m *CheckPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPasswordRequest proto.InternalMessageInfo

func (m *CheckPasswordRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CheckPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type VerifyTokenRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenRequest) Reset()         { *m = VerifyTokenRequest{} }
func (m *VerifyTokenRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenRequest) ProtoMessage()    {}
func (*VerifyTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *VerifyTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenRequest.Unmarshal(m, b)
}
func (m *VerifyTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenRequest.Marshal(b, m, deterministic)
}
func (m *VerifyTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenRequest.Merge(m, src)
}
func (m *VerifyTokenRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenRequest.Size(m)
}
func (m *VerifyTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenRequest proto.InternalMessageInfo

func (m *VerifyTokenRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyTokenResponse struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenResponse) Reset()         { *m = VerifyTokenResponse{} }
func (m *VerifyTokenResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenResponse) ProtoMessage()    {}
func (*VerifyTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *VerifyTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenResponse.Unmarshal(m, b)
}
func (m *VerifyTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenResponse.Marshal(b, m, deterministic)
}
func (m *VerifyTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenResponse.Merge(m, src)
}
func (m *VerifyTokenResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenResponse.Size(m)
}
func (m *VerifyTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenResponse proto.InternalMessageInfo

func (m *VerifyTokenResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type UserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{5}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type CheckPermissionsRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PermissionTags       []string `protobuf:"bytes,2,rep,name=permissionTags,proto3" json:"permissionTags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckPermissionsRequest) Reset()         { *m = CheckPermissionsRequest{} }
func (m *CheckPermissionsRequest) String() string { return proto.CompactTextString(m) }
func (*CheckPermissionsRequest) ProtoMessage()    {}
func (*CheckPermissionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{6}
}

func (m *CheckPermissionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckPermissionsRequest.Unmarshal(m, b)
}
func (m *CheckPermissionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckPermissionsRequest.Marshal(b, m, deterministic)
}
func (m *CheckPermissionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckPermissionsRequest.Merge(m, src)
}
func (m *CheckPermissionsRequest) XXX_Size() int {
	return xxx_messageInfo_CheckPermissionsRequest.Size(m)
}
func (m *CheckPermissionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckPermissionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckPermissionsRequest proto.InternalMessageInfo

func (m *CheckPermissionsRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CheckPermissionsRequest) GetPermissionTags() []string {
	if m != nil {
		return m.PermissionTags
	}
	return nil
}

type ChangePasswordRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	NewPassword          string   `protobuf:"bytes,2,opt,name=newPassword,proto3" json:"newPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangePasswordRequest) Reset()         { *m = ChangePasswordRequest{} }
func (m *ChangePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangePasswordRequest) ProtoMessage()    {}
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{7}
}

func (m *ChangePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangePasswordRequest.Unmarshal(m, b)
}
func (m *ChangePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangePasswordRequest.Merge(m, src)
}
func (m *ChangePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangePasswordRequest.Size(m)
}
func (m *ChangePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangePasswordRequest proto.InternalMessageInfo

func (m *ChangePasswordRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *ChangePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type SetPermissionRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	PermissionTag        string   `protobuf:"bytes,2,opt,name=permissionTag,proto3" json:"permissionTag,omitempty"`
	Grant                bool     `protobuf:"varint,3,opt,name=grant,proto3" json:"grant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetPermissionRequest) Reset()         { *m = SetPermissionRequest{} }
func (m *SetPermissionRequest) String() string { return proto.CompactTextString(m) }
func (*SetPermissionRequest) ProtoMessage()    {}
func (*SetPermissionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{8}
}

func (m *SetPermissionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetPermissionRequest.Unmarshal(m, b)
}
func (m *SetPermissionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetPermissionRequest.Marshal(b, m, deterministic)
}
func (m *SetPermissionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetPermissionRequest.Merge(m, src)
}
func (m *SetPermissionRequest) XXX_Size() int {
	return xxx_messageInfo_SetPermissionRequest.Size(m)
}
func (m *SetPermissionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetPermissionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetPermissionRequest proto.InternalMessageInfo

func (m *SetPermissionRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *SetPermissionRequest) GetPermissionTag() string {
	if m != nil {
		return m.PermissionTag
	}
	return ""
}

func (m *SetPermissionRequest) GetGrant() bool {
	if m != nil {
		return m.Grant
	}
	return false
}

func init() {
	proto.RegisterType((*CheckPasswordRequest)(nil), "auth.CheckPasswordRequest")
	proto.RegisterType((*VerifyTokenRequest)(nil), "auth.VerifyTokenRequest")
	proto.RegisterType((*VerifyTokenResponse)(nil), "auth.VerifyTokenResponse")
	proto.RegisterType((*UserRequest)(nil), "auth.UserRequest")
	proto.RegisterType((*Response)(nil), "auth.Response")
	proto.RegisterType((*LoginResponse)(nil), "auth.LoginResponse")
	proto.RegisterType((*CheckPermissionsRequest)(nil), "auth.CheckPermissionsRequest")
	proto.RegisterType((*ChangePasswordRequest)(nil), "auth.ChangePasswordRequest")
	proto.RegisterType((*SetPermissionRequest)(nil), "auth.SetPermissionRequest")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x51, 0x4f, 0xf2, 0x30,
	0x14, 0xfd, 0x80, 0x0f, 0x32, 0x2e, 0x81, 0x68, 0x41, 0x9d, 0x33, 0x26, 0x4b, 0xa3, 0x86, 0x98,
	0x88, 0x51, 0x9f, 0x8d, 0x0f, 0xe0, 0x83, 0xc6, 0x07, 0x9c, 0xa8, 0xcf, 0x53, 0xaf, 0x63, 0x12,
	0xb6, 0xd9, 0x96, 0x10, 0xff, 0x97, 0x3f, 0xd0, 0x6c, 0xdd, 0x60, 0x85, 0x82, 0xbe, 0xf5, 0xdc,
	0x9e, 0x9e, 0x9e, 0x9e, 0xdb, 0x0b, 0xe0, 0x4e, 0xc4, 0xb0, 0x13, 0xb1, 0x50, 0x84, 0xe4, 0x7f,
	0xbc, 0xa6, 0xb7, 0xd0, 0xea, 0x0e, 0xf1, 0x75, 0xd4, 0x77, 0x39, 0x9f, 0x86, 0xec, 0xcd, 0xc1,
	0xcf, 0x09, 0x72, 0x41, 0xb6, 0xa1, 0x32, 0xe1, 0xc8, 0x6e, 0x7a, 0x66, 0xc1, 0x2e, 0xb4, 0xab,
	0x4e, 0x8a, 0x88, 0x05, 0x46, 0x94, 0x52, 0xcd, 0x62, 0xb2, 0x33, 0xc3, 0xf4, 0x18, 0xc8, 0x13,
	0x32, 0xff, 0xfd, 0x6b, 0x10, 0x8e, 0x30, 0xc8, 0x94, 0x5a, 0x50, 0x16, 0x31, 0x4e, 0x85, 0x24,
	0xa0, 0x27, 0xd0, 0x54, 0xb8, 0x3c, 0x0a, 0x03, 0x8e, 0xab, 0xae, 0xa5, 0xd7, 0x50, 0x7b, 0xe4,
	0xc8, 0x32, 0x4d, 0x0b, 0x8c, 0x78, 0x23, 0x70, 0xc7, 0x98, 0x12, 0x67, 0x78, 0xad, 0x43, 0x00,
	0x23, 0xbb, 0x8a, 0x1e, 0x42, 0xfd, 0x2e, 0xf4, 0xfc, 0xf9, 0xdd, 0x7a, 0xa3, 0xcf, 0xb0, 0x23,
	0x03, 0x42, 0x36, 0xf6, 0x39, 0xf7, 0xc3, 0x80, 0xaf, 0x7d, 0x19, 0x39, 0x82, 0x46, 0x34, 0xe3,
	0x0e, 0x5c, 0x8f, 0x9b, 0x45, 0xbb, 0xd4, 0xae, 0x3a, 0x0b, 0x55, 0x7a, 0x0f, 0x5b, 0xdd, 0xa1,
	0x1b, 0x78, 0xf8, 0xd7, 0xe8, 0x6d, 0xa8, 0x05, 0x38, 0xed, 0xab, 0x6f, 0xcb, 0x97, 0xe8, 0x07,
	0xb4, 0x1e, 0x50, 0xcc, 0x9d, 0xfe, 0xa6, 0x78, 0x00, 0x75, 0xc5, 0x54, 0xaa, 0xa9, 0x16, 0xe3,
	0x67, 0x7a, 0xcc, 0x0d, 0x84, 0x59, 0xb2, 0x0b, 0x6d, 0xc3, 0x91, 0xe0, 0xfc, 0xbb, 0x04, 0xc9,
	0x0f, 0x22, 0x67, 0x50, 0x4e, 0x72, 0x24, 0x9b, 0x9d, 0xe4, 0x77, 0xe5, 0xfa, 0x64, 0x35, 0x65,
	0x49, 0xc9, 0x99, 0xfe, 0x23, 0xa7, 0x71, 0x1b, 0x3c, 0x9f, 0x0b, 0x64, 0xba, 0x53, 0x0d, 0x59,
	0xca, 0x1d, 0xe8, 0xc2, 0xc6, 0x62, 0x13, 0xc8, 0xbe, 0x64, 0xad, 0x68, 0x8e, 0x46, 0xe4, 0x0a,
	0x1a, 0x6a, 0xe0, 0x64, 0x2f, 0x93, 0xd0, 0xb4, 0x41, 0x23, 0x70, 0x09, 0x75, 0x25, 0x5e, 0x62,
	0x49, 0x8a, 0x2e, 0x73, 0xcd, 0xf1, 0x1e, 0xd4, 0x72, 0x5f, 0x9e, 0x98, 0x92, 0xb0, 0x3c, 0x31,
	0xd6, 0xae, 0x66, 0x27, 0x6f, 0x42, 0x19, 0xd8, 0xcc, 0x84, 0x6e, 0x8a, 0x97, 0x4d, 0xbc, 0x54,
	0x92, 0xe1, 0xbf, 0xf8, 0x09, 0x00, 0x00, 0xff, 0xff, 0xb1, 0x0b, 0x9f, 0x06, 0x0a, 0x04, 0x00,
	0x00,
}
